### ISSUE TITLE
Rf bug

### ISSUE THREAD

**Issue by cinouw** [BruceDevices/firmware#323] opened 2024-10-08 18:31 UTC
Hi bruce team

I recently downloaded 1.6.1 firmware to test the frequency detection feature the feature works great but it has a bug

The way the bug happens is when I press next to set the frequency range it dose start to detect the frequency but after that when I try to read the data keeps getting stuck in the frequency detection mode and I can't read any data without restarting the cardputer

**Comment by IncursioHack** [comment] 2024-10-24 18:47
> Hi bruce team
> 
> I recently downloaded 1.6.1 firmware to test the frequency detection feature the feature works great but it has a bug
> 
> The way the bug happens is when I press next to set the frequency range it dose start to detect the frequency but after that when I try to read the data keeps getting stuck in the frequency detection mode and I can't read any data without restarting the cardputer

Please perform a new test on the BETA version. 

Furthermore, keep your device connected to the computer via Serial and collect the Logs. Another point is to inform which device and which RF you are using. This makes it easier for us to reproduce the scenario.

If possible, record a short video about the problem and attach it to this issue.

**Comment by cinouw** [comment] 2024-10-24 23:56
@IncursioHack hi i sorry for the late reply i will retry with beta build

While testing i was using cc1101

**Comment by IncursioHack** [comment] 2024-10-26 13:23
@cinouw 
I need some information to better understand what is happening:
1 - Is the device Cardputer, StickC, CYD...?
2 - Could you carry out the test on the most current version? 1.6.2
3 - Did you select the CC1101 in RF > Config > Module > CC1101?
4 - Have you checked the frequency of the device you are testing? (315mhz, 433.92mhz....)
5 - Could you provide the Serial LOGs together?
6 - Would you have a video to demonstrate what is happening?

**Comment by cinouw** [comment] 2024-10-26 13:39
@IncursioHack Hi

1- I'm using cardputer 
2- the happend on ver. 1.6.1 I didn't try it with 1.6.2 after I try it with 1.6.2 I will inform you 
3- yes I selected cc1101
4- i know the device frequency but I wanted to try the frequency detection feature 
5- I will provide you with the log's after i install 1.6.2
6- ofc I will take a video if the same bug happened in 1.6.2

**Comment by cinouw** [comment] 2024-11-05 00:56
@IncursioHack 

Hi so I recorded this video showcasing the bug 
Note : sorry for my bad english I am still learning

https://drive.google.com/file/d/18JZ702BCXgAoh5e_dWsR7b0peMPeVpmx/view?usp=drivesdk

**Comment by bmorcelli** [comment] 2024-11-05 09:50
Let me help you with a fix, without loosing your bruce.conf (and wifi passwords and stuff saved there)

* RF>Config>Rf Frequency > Type "433.92"
Or 
* RF>Scan/Copy>(Left arrow) Range> choose "387-464 MHz" and you can keep trying receiving the right frequency..

Try not send the signal too close from the receiver, because it is catching the 5 frequencies with good RSSI, and getting the best value of them... so if you are too close, you will have high strength signal on the raise of the "normal curve", and because we are using a wide bandwidth filter here https://github.com/pr3y/Bruce/blob/3415c848c0dbd2aad853925951261b8505d4409d/src/modules/rf/rf.cpp#L499 you probably will catch the wrong frequency..

Try sending the signal from 1,5m away for testing.

**Comment by cinouw** [comment] 2024-11-05 16:24
@IncursioHack 

Hi thanks for the response 

I will retry with the parameters that you mentioned and I will update you

**Comment by bmorcelli** [comment] 2024-12-07 20:22
fixed on beta

**Closed as completed by bmorcelli** 2024-12-07 20:22 UTC
Labels: bug, question
